public class countNumberOfOccurensys {
    
    public static void countStr(){
        String input ='abcdabcdabcdabcd';
        system.debug('***'+input.countMatches('a') +'a'+input.countMatches('b') +'b'+input.countMatches('c') +'c'+input.countMatches('d') +'d');
		//system.debug('***'+input.countMatches('b') +'b');
        //String subStr ='a';
        //input.countMatches(subStr); //should return 1
        
        
    }    
}